In [2]:
import numpy as np

In [3]:
# creating 2 matrices
# A m*n
# B n*p
A = np.array([[1, 2], [3, 4], [5, 6]])
B = np.array([[7, 8, 9], [10, 11, 12]])

In [12]:
#A[row, column]
print(A[1,0])
print(A[0])
print(A[:,0]) # all rows, column 0

3
[1 2]
[1 3 5]


In [5]:
#multiply A nd B
C = np.dot(A, B)
C

array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]])

In [7]:
A@B # same as np.dot(A, B)

array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]])

In [14]:
# Transpose of A
A.T
#or
np.transpose(A)
#or
A.transpose()

array([[1, 3, 5],
       [2, 4, 6]])

In [ ]:
# inverse can only be on a square matrix "np.linalg.inv(C)"
C = np.array([[1,2],[3,4]])
np.linalg.inv(C)



array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [ ]:
# Determinant
np.linalg.det(C)
# if det =0 no inverse, if not equal to 0 invertible

-2.0000000000000004

In [18]:
# rank
np.linalg.matrix_rank(A)

2

In [24]:
# eigen values
np.linalg.eig(C)

EigResult(eigenvalues=array([-0.37228132,  5.37228132]), eigenvectors=array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))